name: Deploy to Local K8s

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Minikube
      run: |
        minikube start
        kubectl apply -f k8s/
